apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dy-http-bin-go
  name: dy-http-bin-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dy-http-bin-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dy-http-bin-go
    spec:
      containers:
        - image: wuxiaoshen/httpbin:v6
          name: http-bin-go
          resources: {}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
              protocol: TCP
              hostPort: 8712
            - containerPort: 9092
              protocol: TCP
              hostPort: 8713
status: {}
